services:
  postgres:
    container_name: postgres-sql-tp
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: trip_planner
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-app
    restart: unless-stopped

  keycloak:
    container_name: keycloak-tp
    image: quay.io/keycloak/keycloak:25.0.4
    ports:
      - 9090:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - spring-app
    command:
      - "start-dev"

networks:
  spring-app:
    driver: bridge

volumes:
  postgres:
    driver: local